package hippodrome.responses;

public enum ResponseType {
    BETTING_CENTRE_ACCEPT_THE_BETS, //
    BETTING_CENTRE_PLACE_A_BET, //
    BETTING_CENTRE_HONOUR_THE_BETS, //
    BETTING_CENTRE_GO_COLLECT_THE_GAINS, //
    CONTROL_CENTRE_START_THE_RACE, //
    CONTROL_CENTRE_ENTERTAIN_THE_RACE, //
    CONTROL_CENTRE_WAIT_FOR_THE_NEXT_RACE, //
    CONTROL_CENTRE_GO_WATCH_THE_RACE, //
    CONTROL_CENTRE_RELAX_A_BIT, //
    CONTROL_CENTRE_SUMMON_HORSES_TO_PADDOCK, //
    CONTROL_CENTRE_PROCEED_TO_PADDOCK, //
    PADDOCK_GO_CHECK_HORSES, //
    PADDOCK_PROCEED_TO_START_LINE, //
    RACING_TRACK_MAKE_A_MOVE, //
    STABLE_PROCEED_TO_STABLE,
    STABLE_PROCEED_TO_STABLE,
    STABLE_SUMMON_HORSES_TO_PADDOCK,
}
